---
title: "wlsd Version History"
author: Charles Ingulli
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  rmarkdown::html_vignette
nocite: '@*'
vignette: >
  %\VignetteIndexEntry{wlsd}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = FALSE,
  comment = "#>"
)
```

# Overview

A table guide to summarize changes between versions.

```{r, echo = FALSE, results = "asis"}
VH <- data.frame(Version = c("0.1.0"),
                 Date = c("12/1/2020"),
                 Author = c("CI"),
                 Summary = c("Initial version of package.")
                 )
knitr::kable(VH, caption = "Table of Changes for wlsd Versions")
```

# Detailed Description

## Version 0.1.0

1. Add the base version of the package with important functions.
2. Add basic package usage vignette. 
3. Add first version history vignette.
4. Ensure package can be used. (This version was successful in preparing my thesis but requires additional details before submission.)
<!---
1. Update LBP data set so variables are parsed in proper formats.

## (Development) Version 0.0.1.2 

1. Update the data set.
2. Add `takefirst()` function.


## (Development) Version 0.0.1.1 

--->

